// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwRCus9Z7ZtPaMjvz3fc5bl0p3jVH8piY',
    appId: '1:1090831130872:web:2defc8a0798e7d36069b0d',
    messagingSenderId: '1090831130872',
    projectId: 'mg-jewelry-e1e1a',
    authDomain: 'mg-jewelry-e1e1a.firebaseapp.com',
    storageBucket: 'mg-jewelry-e1e1a.firebasestorage.app',
    measurementId: 'G-NF5368BZLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSSmUV-7rW92gI-20D7-qfd15cQ2U_ph0',
    appId: '1:1090831130872:android:4b9e6298a6c7542a069b0d',
    messagingSenderId: '1090831130872',
    projectId: 'mg-jewelry-e1e1a',
    storageBucket: 'mg-jewelry-e1e1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa8Nr3IHSPSYZpjtsbB3JJ56ivVPkwFpc',
    appId: '1:1090831130872:ios:ac341a65afefdf5c069b0d',
    messagingSenderId: '1090831130872',
    projectId: 'mg-jewelry-e1e1a',
    storageBucket: 'mg-jewelry-e1e1a.firebasestorage.app',
    iosBundleId: 'com.example.mgJewelry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa8Nr3IHSPSYZpjtsbB3JJ56ivVPkwFpc',
    appId: '1:1090831130872:ios:ac341a65afefdf5c069b0d',
    messagingSenderId: '1090831130872',
    projectId: 'mg-jewelry-e1e1a',
    storageBucket: 'mg-jewelry-e1e1a.firebasestorage.app',
    iosBundleId: 'com.example.mgJewelry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwRCus9Z7ZtPaMjvz3fc5bl0p3jVH8piY',
    appId: '1:1090831130872:web:ec60196b69af34e7069b0d',
    messagingSenderId: '1090831130872',
    projectId: 'mg-jewelry-e1e1a',
    authDomain: 'mg-jewelry-e1e1a.firebaseapp.com',
    storageBucket: 'mg-jewelry-e1e1a.firebasestorage.app',
    measurementId: 'G-0GMDC23PMM',
  );
}
